"""Atualizando o banco

Revision ID: 31113f3f2206
Revises: 9afa05f3889b
Create Date: 2026-06-02 16:46:58.228825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31113f3f2206'
down_revision: Union[str, Sequence[str], None] = '9afa05f3889b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support "DROP COLUMN IF EXISTS" directly.
    # Check at runtime whether the column exists and only then drop it.
    bind = op.get_bind()
    try:
        rows = bind.execute("PRAGMA table_info(clientes)").fetchall()
        cols = [r[1] for r in rows]
    except Exception:
        cols = []

    if 'matricula' in cols:
        op.drop_column('clientes', 'matricula')
    # Use batch_alter_table for SQLite which doesn't support ALTER COLUMN
    with op.batch_alter_table('movimentacoes') as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('produtos') as batch_op:
        batch_op.alter_column('estoque_atual',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    # Reverse changes using batch_alter_table for SQLite
    with op.batch_alter_table('produtos') as batch_op:
        batch_op.alter_column('estoque_atual',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('movimentacoes') as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('clientes', sa.Column('matricula', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
