"""Atualizando o banco

Revision ID: 31113f3f2206
Revises: 9afa05f3889b
Create Date: 2026-06-02 16:46:58.228825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31113f3f2206'
down_revision: Union[str, Sequence[str], None] = '9afa05f3889b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'matricula')
    op.alter_column('movimentacoes', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('produtos', 'estoque_atual',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.alter_column('produtos', 'estoque_atual',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('movimentacoes', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('clientes', sa.Column('matricula', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
