"""adicionado campo nome e senah no bando de dados

Revision ID: 36fddc4a487c
Revises: a1ff08ea5f23
Create Date: 2026-05-26 10:16:32.343308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fddc4a487c'
down_revision: Union[str, Sequence[str], None] = 'a1ff08ea5f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=255), nullable=False))
    op.add_column('usuarios', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha_hash')
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
