"""Criando tabelas de movimentação

Revision ID: 4bdaf7d647f2
Revises: 5556c0d71c11
Create Date: 2026-06-02 10:45:28.027423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdaf7d647f2'
down_revision: Union[str, Sequence[str], None] = '5556c0d71c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipo_de_movimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    op.alter_column('produtos', 'estoque_atual',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    # Skip alter_column for SQLite compatibility
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    # ### end Alembic commands ###
