"""reset inicial

Revision ID: 5f6baec55027
Revises: e363c1529406
Create Date: 2026-06-08 10:54:01.502077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6baec55027'
down_revision: Union[str, Sequence[str], None] = 'e363c1529406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'cursos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cursos', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
