"""Remover matricula e adicionar email e turmas no cliente

Revision ID: 9afa05f3889b
Revises: 679e5e6cb2eb
Create Date: 2026-06-02 16:28:52.187328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afa05f3889b'
down_revision: Union[str, Sequence[str], None] = '679e5e6cb2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('clientes', sa.Column('turmas', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'turmas')
    op.drop_column('clientes', 'email')
    # ### end Alembic commands ###
