"""tabela-variacao

Revision ID: b4b3aaf0d58f
Revises: 5f6baec55027
Create Date: 2026-07-28 15:55:50.015077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b3aaf0d58f'
down_revision: Union[str, Sequence[str], None] = '5f6baec55027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=10), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variacoes_id'), 'variacoes', ['id'], unique=False)
    op.drop_column('produtos', 'estoque_atual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque_atual', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_variacoes_id'), table_name='variacoes')
    op.drop_table('variacoes')
    # ### end Alembic commands ###
