"""Adiciona matricula ao cliente

Revision ID: b7e2c3d4f5a6
Revises: 31113f3f2206
Create Date: 2026-06-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e2c3d4f5a6'
down_revision: Union[str, Sequence[str], None] = '31113f3f2206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('matricula', sa.VARCHAR(length=50), nullable=True))
    op.create_index(op.f('ix_clientes_matricula'), 'clientes', ['matricula'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_matricula'), table_name='clientes')
    op.drop_column('clientes', 'matricula')
    # ### end Alembic commands ###
