"""Atualização armários - remover semestre e adicionar campos de curso, turma, email

Revision ID: c52d1e8f9a34
Revises: 9c1e8af317fb
Create Date: 2026-08-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52d1e8f9a34'
down_revision: Union[str, Sequence[str], None] = '9c1e8af317fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armarios', sa.Column('nome_curso', sa.String(length=100), nullable=True))
    op.add_column('armarios', sa.Column('turma', sa.String(length=50), nullable=True))
    op.add_column('armarios', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_column('armarios', 'semestre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armarios', sa.Column('semestre', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('armarios', 'email')
    op.drop_column('armarios', 'turma')
    op.drop_column('armarios', 'nome_curso')
    # ### end Alembic commands ###
