"""adicionar_imagem_variacoes

Revision ID: dbd900df15de
Revises: d7e4f2a1c9b8
Create Date: 2026-09-01 13:40:45.628542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd900df15de'
down_revision: Union[str, Sequence[str], None] = 'd7e4f2a1c9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variacoes', sa.Column('imagem_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variacoes', 'imagem_path')
    # ### end Alembic commands ###
